### ISSUE TITLE
It's can not compile in the platformio under vscode?

### ISSUE THREAD

**Issue by KiraVerSace** [philj404/SimpleSerialShell#1]
<img width="788" alt="iShot2020-10-16 02 19 40" src="https://user-images.githubusercontent.com/55439370/96170383-16db3180-0f56-11eb-8e7f-17b13b2ced2d.png">

**Comment by philj404** [comment]
Hmm.

I have not tried to compile in this environment -- I have only used the Arduino IDE.

Perhaps the Arduino "Stream" interface is not recognized in your platformio environment?  I think it is included as part of "Arduino.h" (in the Arduino IDE).

You may need to change the code to work in your particular environment.  I tried to keep it simple to make any changes like this easier.  Maybe you could change 

If you can learn how to make changes to add support for platformio I would LOVE to read a pull request to add platformio support.

**Comment by KiraVerSace** [comment]
I think there may some virtual functions from stream class cause it, would you like to contiune support this tool  make it more stronger!!!

**Comment by philj404** [comment]
At this time I am only willing to support the Arduino platform.  It is the environment I use.

I do not use the platformio/vscode environment.  I cannot see error messages from platformio.  I cannot test changes in platformio.  

I would consider making a compatible change if you have something which can work in both environments.

One of my goals is to ensure SimpleSerialShell stays SIMPLE (as a teaching tool).  This makes it easier to understand how it works and THEN allows you to customize it to your particular needs.

I am interested in changes you might have to make to get SimpleSerialShell working in your environment.  Others may be able to learn from your changes.  Perhaps they could use a similar technique for other environments.

**Comment by philj404** [comment]
I have made some changes which might improve support for the esp32 platform.

**Comment by KiraVerSace** [comment]
> I have made some changes which might improve support for the esp32 platform.

most people use the stm32duino, I use that, HaHa
I suggest you can add prompt like ' >'

and add auto complete command and history command features.

Thank you for your code, your project shell is the best in github as it's name
simple and functional,It's very easy to read

**Comment by KiraVerSace** [comment]
now i use the shell write by myself but it's not stable , but you can read it .
I will use yours in my project later
https://github.com/KiraVerSace/XShell

**Comment by philj404** [comment]
1. Thanks to **.../.github/workflows/githubci.yml** and **adafruit/ci-arduino** I was able to build the shell for boards I do not have (such as stm32).  I still cannot _test_ those builds, but at least there is something to download and try now.

2. The "command prompt and command history" suggestion is more of a creeping feature than a build issue.  It could consume a lot of code space and RAM.  I would like to leave most space available for the actual application.  If you need those features, have you considered a Raspberry Pi with the Linux bash shell? :)

3. I looked at your XShell code... it looks like it would not leave much room for other code on my older Arduino Duemilanove (from 2009).  I hope it works out for your more powerful processor.  Good luck!

**Comment by KiraVerSace** [comment]
> 1. Thanks to **.../.github/workflows/githubci.yml** and **adafruit/ci-arduino** I was able to build the shell for boards I do not have (such as stm32).  I still cannot _test_ those builds, but at least there is something to download and try now.
> 2. The "command prompt and command history" suggestion is more of a creeping feature than a build issue.  It could consume a lot of code space and RAM.  I would like to leave most space available for the actual application.  If you need those features, have you considered a Raspberry Pi with the Linux bash shell? :)
> 3. I looked at your XShell code... it looks like it would not leave much room for other code on my older Arduino Duemilanove (from 2009).  I hope it works out for your more powerful processor.  Good luck!

Thank you for your reply.
I use it in my project do not use as a geek.
In fact, stm32 mcu is cheaper as the Duemilanove thant you mentioned, and with more ram and flash, you can foucus on your project without wondering the  size of your program.

Haha, if you in China, I will give you serval stm32boards as gifts, I have to many!

At last, I suggest you a way to develop it, you can use vscode+platformio to develop arduino or esp32 or other mcus that under the platform of Arduino, it's very convenientily and more better than the offical IDE.

BEST REGARDS
