### ISSUE TITLE
Wrong function dispatched when one command starts with another command.  

### ISSUE THREAD

**Issue by brucemack** [philj404/SimpleSerialShell#28]
For example, if commands "setroute" and "setrouteremote" are both registered (with documentation) the wrong function will be executed under certain circumstances.  This defect was introduced by @brucemack during the work on the help feature.  Fix will follow.

**Comment by philj404** [comment]
Should be fixed with the v0.9.2 release.

**Comment by brucemack** [comment]
Thanks Phil, sorry for the hassle on that.

Bruce
