### ISSUE TITLE
Not Working (UNO R3)

### ISSUE THREAD

**Issue by rvneXe** [philj404/SimpleSerialShell#37]
I've uploaded AdjustableBlink on my arduino.
this message appears at first: 
![image](https://user-images.githubusercontent.com/89677246/230382654-0edc4802-b453-428d-b316-8790e4bcaa07.png)

and then nothing happens when i send "setTogglePeriod" commands

**Comment by philj404** [comment]
I have seen that symptom too.

What is happening is the UNO and the IDE's "Serial Monitor" are each using different baud rates.

Make sure the two baud rates match -- for example make sure they are _both_ set to 9600 baud.  Depending on the application, you may be able to see text at higher baud rates, even 115200 baud.

**Comment by philj404** [comment]
Haven't heard back -- I suspect the problem is resolved.

**Comment by rvneXe** [comment]
Sorry, I couldn't test for some reasons.
