### ISSUE TITLE
Add ability for comment lines to be ignored

### ISSUE THREAD

**Issue by paulhayes** [philj404/SimpleSerialShell#38]
Thanks for making such a great library. Incredibly useful. Especially because you have both Serial attachment and a more manual ```shell.execute(line);``` features. 

There's only one feature that I think would be really useful, and that's the ability to register a comment character like "#", that means a line is skipped over immediately without a command not found message being outputted.

**Comment by philj404** [comment]
Try this:

Create a "do nothing" command and add it with `shell.addCommand(F("#"), doNothing);`

If you would rather use a different comment marker, you can change it.

**Comment by philj404** [comment]
Instead add a "do nothing" command and as suggested above.
